// <auto-generated />
using System;
using BNS360.Reposatory.Data.AppBusniss;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BNS360.Reposatory.data.appbusniss.migrations
{
    [DbContext(typeof(AppBusnissDbContext))]
    partial class AppBusnissDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BNS360.Core.Entities.Busniss", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Busnisses");
                });

            modelBuilder.Entity("BNS360.Core.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BNS360.Core.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusnissId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecoundPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirdPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BusnissId")
                        .IsUnique();

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("BNS360.Core.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("BusnissId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal");

                    b.HasKey("Id");

                    b.HasIndex("BusnissId")
                        .IsUnique();

                    b.ToTable("Location");
                });

            modelBuilder.Entity("BNS360.Core.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusnissId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Rate")
                        .HasColumnType("real");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BusnissId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("BNS360.Core.Entities.WorkTime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusnissId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("End")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("Start")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("BusnissId");

                    b.ToTable("WorkTime");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityRole");

                    b.HasData(
                        new
                        {
                            Id = "2b414bc4-e7f4-417b-9fb7-899f28f6caec",
                            ConcurrencyStamp = "35bebd76-1e74-499e-a242-8a56cce8262a",
                            Name = "Default",
                            NormalizedName = "DEFAULT"
                        },
                        new
                        {
                            Id = "8a6290af-e192-4def-b22d-bcc63ad0855e",
                            ConcurrencyStamp = "87b3a328-b0b0-4037-af16-d66f6f3d2338",
                            Name = "BusinssOwner",
                            NormalizedName = "BUSINSSOWNER"
                        },
                        new
                        {
                            Id = "31940441-c040-43b7-9551-5ad4a033f9d7",
                            ConcurrencyStamp = "80d84e4e-de5c-413f-bf10-776b4d59eef0",
                            Name = "ServiceProvider",
                            NormalizedName = "SERVICEPROVIDER"
                        });
                });

            modelBuilder.Entity("BNS360.Core.Entities.Busniss", b =>
                {
                    b.HasOne("BNS360.Core.Entities.Category", null)
                        .WithMany("Busnisses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BNS360.Core.Entities.Contact", b =>
                {
                    b.HasOne("BNS360.Core.Entities.Busniss", null)
                        .WithOne("ContactInfo")
                        .HasForeignKey("BNS360.Core.Entities.Contact", "BusnissId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BNS360.Core.Entities.Location", b =>
                {
                    b.HasOne("BNS360.Core.Entities.Busniss", null)
                        .WithOne("Location")
                        .HasForeignKey("BNS360.Core.Entities.Location", "BusnissId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BNS360.Core.Entities.Review", b =>
                {
                    b.HasOne("BNS360.Core.Entities.Busniss", null)
                        .WithMany("Reviews")
                        .HasForeignKey("BusnissId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BNS360.Core.Entities.WorkTime", b =>
                {
                    b.HasOne("BNS360.Core.Entities.Busniss", null)
                        .WithMany("WorkTime")
                        .HasForeignKey("BusnissId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BNS360.Core.Entities.Busniss", b =>
                {
                    b.Navigation("ContactInfo");

                    b.Navigation("Location");

                    b.Navigation("Reviews");

                    b.Navigation("WorkTime");
                });

            modelBuilder.Entity("BNS360.Core.Entities.Category", b =>
                {
                    b.Navigation("Busnisses");
                });
#pragma warning restore 612, 618
        }
    }
}
